project_id = "byhoziuwsaxpemmyhauo"

[functions.sync-google-contacts]
verify_jwt = true

[functions.generate-message]
verify_jwt = false

[functions.fetch-linkedin]
verify_jwt = false

[functions.update-google-contact]
verify_jwt = true

[functions.create-google-contact]
verify_jwt = true

[functions.refresh-google-token]
verify_jwt = true

[functions.google-oauth-url]
verify_jwt = true

[functions.google-oauth-callback]
verify_jwt = false

[functions.start-google-contacts-sync]
verify_jwt = false

[functions.get-sync-job-status]
verify_jwt = false

[functions.cancel-sync-job]
verify_jwt = false

[functions.worker-google-contacts-sync]
verify_jwt = false
