project_id = "byhoziuwsaxpemmyhauo"

[functions.sync-google-contacts]
verify_jwt = true

[functions.generate-message]
verify_jwt = false

[functions.fetch-linkedin]
verify_jwt = false

[functions.update-google-contact]
verify_jwt = true

[functions.create-google-contact]
verify_jwt = true

[functions.backfill-contact-schedule]
verify_jwt = true
